# Generated by Django 2.2.4 on 2020-12-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whcapp', '0006_merge_20201226_1834'),
        ('whcapp', '0006_merge_20201226_2007'),
    ]

    operations = [
    ]
